apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feminist-rodent-go-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/feminist-rodent-go/overlays/development
    repoURL: https://github.com/rhtap-rhdh-qe/feminist-rodent-go-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-e2e-ci-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
