apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: feminist-rodent-go 
  janus-idp.io/tekton: feminist-rodent-go
  backstage.io/kubernetes-id: feminist-rodent-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: feminist-rodent-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  