apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: feminist-rodent-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: feminist-rodent-go 
  name: feminist-rodent-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: feminist-rodent-go 
